/-
# Natural-number interpretations of 𝒯 (Section 12.1): the monoid on `Q_s`, `u♯`, and elements of intervals `Θ`

Lemmas 12.1 and 12.4 of the paper, in the form restricted to the case where **all components of the lift are 0/1** (the hypothesis
(H2^prod), `H2Prod`, of Theorem 10.10), for any occurrence of `u♯`. The statements concern the automaton `ValAuto Q` only and depend neither on
the rewriting rules nor on 𝒯 (downstream they are applied to `liftT A`). Notation: `B_w`, `D^C_w`, `μ(w)` are `N_w`, `N^C_w`, `N̄ˢ_w` of the paper.

* **§1 General finite monoids**: the two-sided ideal `span` generated by `s`, **Lemma 12.1 (ii)** (`left_cancel`: if `s ∈ \mathcal K` and
  `se = s`, then `y ↦ sy` is injective on `{y | ey = y}`), **Lemma 12.1 (ii)** (`eMe_inH`: the elements of `e\mathcal Me` are elements of the group
  with identity `e`; a restatement of `MinIdeal.inH_of_minIdeal` of the arctic part, Lemma 6.2), right stability `right_stable` (if `s ∈ \mathcal K`,
  one can return from `s m` to `s` by a right product; used for the recurrence of DFA states), `Θ` (`theta`) and `theta_eq` (the uniqueness part of Lemma 12.4).
* **§2 `Q_s`**: `InZ A q` (`q` lies in a relevant, survivable 0/1 component. In an earlier, longer argument the set was defined by "survivable with
  `Λ_C = 0`", whose products are 0/1 by a lemma of that argument; here it is defined by the 0/1 condition). The index type `ZIdx A`.
* **§3 The monoid `\mathcal M`**: `muZ A w` (a Boolean matrix on the indices of `Q_s`; entries between different components are dropped).
  `muZ_append` (from 0/1 products to Boolean products; components are not crossed, since they are closed along paths), `muMon`,
  the correspondence with 0/1 entries `DxN_eq_ite_muZ` (inside a component of `Q_s`, `(B_w)_{xy} = [μ(w)_{xy}]`), and one DFA step `muStep`.
* **§4 `u♯`** (`Sharp`): its type `e` is an idempotent of the minimal ideal `\mathcal K` of `\mathcal M`, and `u♯` is non-empty and contains `u*`.
  `exists_sharp`. **The killing property** `Sharp.kills`: if all components are 0/1, every component of relevant indices outside `Q_s` (trivial components
  and non-survivable 0/1 components) has `D^C_{u♯} = 0` (`ustar_kills`, `DC_eq_zero_of_infix` of `CompartmentPi.lean`).
* **§5 Elements of intervals** (Lemma 12.4, for **any occurrence, not a chosen one**): `occAt`, `theta_spec`
  (`μ(ω_{(a,b]}) = Θ(s_a, μ(ω_{(a,r]}), s_b)`, where `r` is the end of any occurrence of `u♯` in `(a, b]`),
  and the weight of a long sojourn `stay_eq_theta` (`(B_{ω_{(a,b]}})_{xy} = [Θ(…)_{xy}]`).
-/
import CollatzProof.Arctic.Nat.CompartmentPi

namespace Collatz.Arctic.NatQ5.W3c

open Collatz.Arctic Collatz.Arctic.NatQ5 Matrix
open Collatz.Arctic.MinIdeal (IsIdeal IsMinIdeal InH BRel)

set_option linter.unusedSectionVars false

/-! ## §1 General finite monoids: left cancellation and `Θ` (the algebra of Lemmas 12.1 and 12.4) -/

section General

variable {α : Type*} [Monoid α]

/-- The two-sided ideal `Mon s Mon` generated by `s`. -/
def span (Mon : Submonoid α) (s : α) : Set α := {z | ∃ a ∈ Mon, ∃ b ∈ Mon, z = a * s * b}

theorem isIdeal_span {Mon : Submonoid α} {s : α} (hs : s ∈ Mon) : IsIdeal Mon (span Mon s) := by
  refine ⟨⟨s, 1, Mon.one_mem, 1, Mon.one_mem, by simp⟩, ?_, ?_⟩
  · rintro z ⟨a, ha, b, hb, rfl⟩
    exact Mon.mul_mem (Mon.mul_mem ha hs) hb
  · rintro x hx z ⟨a, ha, b, hb, rfl⟩
    exact ⟨⟨x * a, Mon.mul_mem hx ha, b, hb, by simp [mul_assoc]⟩,
      ⟨a, ha, b * x, Mon.mul_mem hb hx, by simp [mul_assoc]⟩⟩

/-- An element of the minimal ideal lies in the ideal generated by any element `s` of the minimal ideal. -/
theorem mem_span_of_minIdeal {Mon : Submonoid α} {K : Set α} (hK : IsMinIdeal Mon K) {s x : α}
    (hs : s ∈ K) (hx : x ∈ K) : x ∈ span Mon s :=
  hK.2 _ (isIdeal_span (hK.1.2.1 hs)) hx

theorem minIdeal_mul_mem_left {Mon : Submonoid α} {K : Set α} (hK : IsMinIdeal Mon K) {x y : α}
    (hx : x ∈ Mon) (hy : y ∈ K) : x * y ∈ K := (hK.1.2.2 x hx y hy).1

theorem minIdeal_mul_mem_right {Mon : Submonoid α} {K : Set α} (hK : IsMinIdeal Mon K) {x y : α}
    (hx : x ∈ Mon) (hy : y ∈ K) : y * x ∈ K := (hK.1.2.2 x hx y hy).2

/-- **Lemma 12.1 (ii)** (left cancellation): if `s ∈ \mathcal K` and `se = s`, then `y ↦ sy` is injective on `{y | ey = y}` (which contains `e\mathcal M`).
The proof is that of the paper: from `e = asb`, `c := eas ∈ e\mathcal Me` has the right inverse `ebe`, which is a two-sided inverse by finiteness. -/
theorem left_cancel [Finite α] {Mon : Submonoid α} {K : Set α} (hK : IsMinIdeal Mon K) {e : α} (heK : e ∈ K)
    (he : e * e = e) {s : α} (hs : s ∈ K) (hse : s * e = s) {y y' : α} (hy : e * y = y) (hy' : e * y' = y')
    (h : s * y = s * y') : y = y' := by
  obtain ⟨a, _, b, _, hab⟩ := mem_span_of_minIdeal hK hs heK
  have hcd : (e * a * s) * (e * b * e) = e := by
    calc (e * a * s) * (e * b * e) = e * a * (s * e) * b * e := by simp only [mul_assoc]
      _ = e * (a * s * b) * e := by rw [hse]; simp only [mul_assoc]
      _ = e := by rw [← hab, he, he]
  have hx : (e * a * s) * e = e * a * s := by rw [mul_assoc (e * a) s e, hse]
  have hy2 : e * (e * b * e) = e * b * e := by simp only [← mul_assoc, he]
  have hdc := MinIdeal.mul_eq_comm_of_finite he hx hy2 hcd
  calc y = e * y := hy.symm
    _ = (e * b * e) * (e * a * s) * y := by rw [hdc]
    _ = (e * b * e) * (e * a) * (s * y) := by simp only [mul_assoc]
    _ = (e * b * e) * (e * a) * (s * y') := by rw [h]
    _ = (e * b * e) * (e * a * s) * y' := by simp only [mul_assoc]
    _ = e * y' := by rw [hdc]
    _ = y' := hy'

/-- **Lemma 12.1 (ii)**: if `x ∈ \mathcal M`, then `exe` is an element of the group `H_e` with identity `e` (`e\mathcal Me` is a group, `𝒢_e` in the paper). -/
theorem eMe_inH [Finite α] {Mon : Submonoid α} {K : Set α} (hK : IsMinIdeal Mon K) {e : α} (heK : e ∈ K)
    (he : e * e = e) {x : α} (hx : x ∈ Mon) : InH e (e * x * e) :=
  MinIdeal.inH_of_minIdeal hK heK he hx

/-- **Right stability**: if `s ∈ \mathcal K` and `m ∈ \mathcal M`, then `s m c = s` for some `c ∈ \mathcal M` (`s\mathcal M` is a minimal right ideal).
Proof: `s = a(sm)b`; for an idempotent power `f = x^n` of `x := mb`, `s = a^n s f`, hence `sf = s` and `s = (sm)(b x^{n-1})`. -/
theorem right_stable [Finite α] {Mon : Submonoid α} {K : Set α} (hK : IsMinIdeal Mon K) {s : α} (hs : s ∈ K)
    {m : α} (hm : m ∈ Mon) : ∃ c ∈ Mon, s * m * c = s := by
  have htK : s * m ∈ K := minIdeal_mul_mem_right hK hm hs
  obtain ⟨a, ha, b, hb, hab⟩ := mem_span_of_minIdeal hK htK hs
  set x := m * b
  have hx : x ∈ Mon := Mon.mul_mem hm hb
  have h1 : s = a * s * x := by
    calc s = a * (s * m) * b := hab
      _ = a * s * x := by simp only [x, mul_assoc]
  have hpow : ∀ n, s = a ^ n * s * x ^ n := by
    intro n
    induction n with
    | zero => simp
    | succ n ih =>
      calc s = a ^ n * s * x ^ n := ih
        _ = a ^ n * (a * s * x) * x ^ n := by rw [← h1]
        _ = a ^ (n + 1) * s * x ^ (n + 1) := by rw [pow_succ a n, pow_succ' x n]; simp only [mul_assoc]
  obtain ⟨n, hn, hidem⟩ := MinIdeal.exists_idem_pow x
  have hsf : s * x ^ n = s := by
    calc s * x ^ n = a ^ n * s * x ^ n * x ^ n := by rw [← hpow n]
      _ = a ^ n * s * (x ^ n * x ^ n) := by simp only [mul_assoc]
      _ = s := by rw [hidem, ← hpow n]
  obtain ⟨n', rfl⟩ := Nat.exists_eq_add_of_lt hn
  refine ⟨b * x ^ (0 + n'), Mon.mul_mem hb (Mon.pow_mem hx _), ?_⟩
  calc s * m * (b * x ^ (0 + n')) = s * (m * b) * x ^ (0 + n') := by simp only [mul_assoc]
    _ = s * x ^ (0 + n' + 1) := by rw [pow_succ' x (0 + n')]; simp only [x, mul_assoc]
    _ = s := hsf

open Classical in
/-- **`Θ`** (the fixed function of Lemma 12.4): `Θ(s, A, s') := A y`, where `y` satisfies `ey = y` and `sAy = s'` (`A` if there is none). -/
noncomputable def theta (e s A s' : α) : α :=
  if h : ∃ y, e * y = y ∧ s * A * y = s' then A * h.choose else A

/-- **Uniqueness of `Θ`** (the core of the proof of Lemma 12.4): if `s ∈ \mathcal M`, `A ∈ \mathcal M`, `Ae = A` and `ey₀ = y₀`, then
`Θ(s, A, sAy₀) = Ay₀`. -/
theorem theta_eq [Finite α] {Mon : Submonoid α} {K : Set α} (hK : IsMinIdeal Mon K) {e : α} (heK : e ∈ K)
    (he : e * e = e) {s A : α} (hs : s ∈ Mon) (hA : A ∈ Mon) (hAe : A * e = A) {y₀ : α} (hy₀ : e * y₀ = y₀) :
    theta e s A (s * A * y₀) = A * y₀ := by
  have hex : ∃ y, e * y = y ∧ s * A * y = s * A * y₀ := ⟨y₀, hy₀, rfl⟩
  unfold theta
  rw [dite_eq_left_of_eq_true (eq_true hex)]
  have hAK : A ∈ K := by rw [← hAe]; exact minIdeal_mul_mem_left hK hA heK
  have hsAK : s * A ∈ K := minIdeal_mul_mem_left hK hs hAK
  have hsAe : s * A * e = s * A := by rw [mul_assoc, hAe]
  have := left_cancel hK heK he hsAK hsAe hex.choose_spec.1 hy₀ hex.choose_spec.2
  rw [this]

end General

/-! ## §2 `Q_s`: relevant, survivable 0/1 components -/

section Z

variable {Q : Type*} [Fintype Q] [DecidableEq Q] (A : ValAuto Q)

/-- **`q ∈ Q_s`**: `q` is relevant, and its strongly connected component has an internal edge (it is a component), is survivable and is 0/1. -/
def InZ (q : Q) : Prop :=
  Rel A q ∧ HasEdge A (sccOf A q) ∧ Survivable A (sccOf A q) ∧ ZeroOne A (sccOf A q)

theorem inZ_of_mem {q x : Q} (hq : InZ A q) (hx : x ∈ sccOf A q) : InZ A x := by
  have h := sccOf_eq_of_mem A hx
  refine ⟨rel_of_mem_sccOf A hq.1 hx, ?_, ?_, ?_⟩
  · rw [h]; exact hq.2.1
  · rw [h]; exact hq.2.2.1
  · rw [h]; exact hq.2.2.2

theorem isComp_of_inZ {q : Q} (hq : InZ A q) : IsComp A (sccOf A q) := ⟨⟨q, hq.1, rfl⟩, hq.2.1⟩

/-- If all components are 0/1, then `q ∈ Q_s` is the same as "relevant, a component, survivable". -/
theorem inZ_iff_of_zeroOne (h01 : ∀ C, IsComp A C → ZeroOne A C) (q : Q) :
    InZ A q ↔ Rel A q ∧ HasEdge A (sccOf A q) ∧ Survivable A (sccOf A q) :=
  ⟨fun h => ⟨h.1, h.2.1, h.2.2.1⟩, fun h => ⟨h.1, h.2.1, h.2.2, h01 _ ⟨⟨q, h.1, rfl⟩, h.2.1⟩⟩⟩

/-- The index type of `Q_s`. -/
abbrev ZIdx := {q : Q // InZ A q}

end Z

/-! ## §3 The monoid `\mathcal M` -/

section Mon

variable {Q : Type*} [Fintype Q] [DecidableEq Q] (A : ValAuto Q)

/-- **`μ(w)`** (`N̄ˢ_w` of Section 12.1: the tuple `μ(w) := (D^C_w)_{C ⊆ Q_s}` of an earlier written form, written as one Boolean matrix on the indices of `Q_s`):
`x, y` lie in the same component and `(B_w)_{xy} ≥ 1`. The components are 0/1, so this carries the same information as `D^C_w` (`DxN_eq_ite_muZ`). -/
def muZ (w : List (Fin 2)) : BRel (ZIdx A) := fun x y => y.1 ∈ sccOf A x.1 ∧ 1 ≤ Rigid.DxN A.B w x.1 y.1

theorem muZ_apply (w : List (Fin 2)) (x y : ZIdx A) :
    muZ A w x y ↔ y.1 ∈ sccOf A x.1 ∧ 1 ≤ Rigid.DxN A.B w x.1 y.1 := Iff.rfl

theorem muZ_nil : muZ A [] = 1 :=
  MinIdeal.BRel.ext fun x y => by
    rw [MinIdeal.BRel.one_apply, muZ_apply]
    constructor
    · rintro ⟨_, h⟩
      by_contra hne
      have : x.1 ≠ y.1 := fun h' => hne (Subtype.ext h')
      simp [this] at h
    · rintro rfl
      exact ⟨self_mem_sccOf A x.1, by simp⟩

/-- **From 0/1 products to Boolean products**: `μ(w w') = μ(w) μ(w')`. The middle index lies in the same component, since components are closed along paths. -/
theorem muZ_append (w w' : List (Fin 2)) : muZ A (w ++ w') = muZ A w * muZ A w' :=
  MinIdeal.BRel.ext fun x y => by
    rw [MinIdeal.BRel.mul_apply, muZ_apply]
    constructor
    · rintro ⟨hy, h⟩
      obtain ⟨k, h1, h2⟩ := exists_mid_of_append h
      have hk : k ∈ sccOf A x.1 :=
        sccOf_convex A x.1 x.1 (self_mem_sccOf A x.1) y.1 hy k (conn_of_DxN A h1) (conn_of_DxN A h2)
      refine ⟨⟨k, inZ_of_mem A x.2 hk⟩, ⟨hk, h1⟩, ?_, h2⟩
      rw [sccOf_eq_of_mem A hk]; exact hy
    · rintro ⟨c, ⟨hc, h1⟩, hy, h2⟩
      refine ⟨?_, one_le_DxN_append h1 h2⟩
      rw [← sccOf_eq_of_mem A hc]; exact hy

theorem muZ_cons (b : Fin 2) (w : List (Fin 2)) : muZ A (b :: w) = muZ A [b] * muZ A w := by
  rw [← muZ_append]; rfl

theorem muZ_flatten_replicate (n : ℕ) (w : List (Fin 2)) :
    muZ A (List.replicate n w).flatten = muZ A w ^ n := by
  induction n with
  | zero => simp [muZ_nil]
  | succ n ih => rw [List.replicate_succ, List.flatten_cons, muZ_append, ih, pow_succ']

/-- The monoid `\mathcal M` (generated by `μ(0)` and `μ(1)`; it equals the image of `μ`: `muZ_mem`, `exists_muZ_of_mem`). -/
def muMon : Submonoid (BRel (ZIdx A)) := Submonoid.closure {muZ A [0], muZ A [1]}

theorem muZ_mem (w : List (Fin 2)) : muZ A w ∈ muMon A := by
  induction w with
  | nil => rw [muZ_nil]; exact (muMon A).one_mem
  | cons b w ih =>
    rw [muZ_cons]
    refine (muMon A).mul_mem ?_ ih
    apply Submonoid.subset_closure
    fin_cases b
    · exact Or.inl rfl
    · exact Or.inr rfl

theorem exists_muZ_of_mem {X : BRel (ZIdx A)} (hX : X ∈ muMon A) : ∃ w, muZ A w = X := by
  induction hX using Submonoid.closure_induction with
  | mem x hx =>
    rcases hx with rfl | rfl
    · exact ⟨[0], rfl⟩
    · exact ⟨[1], rfl⟩
  | one => exact ⟨[], muZ_nil A⟩
  | mul x y _ _ hx hy =>
    obtain ⟨w, rfl⟩ := hx
    obtain ⟨w', rfl⟩ := hy
    exact ⟨w ++ w', muZ_append A w w'⟩

open Classical in
/-- **Correspondence with the 0/1 entries**: inside a component of `Q_s` (`y ∈ sccOf x`), `(B_w)_{xy} = [μ(w)_{xy}]`. -/
theorem DxN_eq_ite_muZ {x y : ZIdx A} (hxy : y.1 ∈ sccOf A x.1) (w : List (Fin 2)) :
    Rigid.DxN A.B w x.1 y.1 = if muZ A w x y then 1 else 0 := by
  have h01 : Rigid.DxN A.B w x.1 y.1 ≤ 1 := by
    have := x.2.2.2.2 w ⟨x.1, self_mem_sccOf A x.1⟩ ⟨y.1, hxy⟩
    rwa [DC_apply] at this
  by_cases h : 1 ≤ Rigid.DxN A.B w x.1 y.1
  · have hm : muZ A w x y := ⟨hxy, h⟩
    simp only [hm, ↓reduceIte]; omega
  · have hm : ¬ muZ A w x y := fun h' => h h'.2
    simp only [hm, ↓reduceIte]; omega

open Classical in
/-- The form in terms of the entries of the product on a component: the `(x, y)` entry of `D^C_w` is `[μ(w)_{xy}]` (`C = sccOf q`, `q ∈ Q_s`). -/
theorem DC_eq_ite_muZ {q : Q} (hq : InZ A q) (w : List (Fin 2)) (x y : sccOf A q) :
    DC A (sccOf A q) w x y =
      if muZ A w ⟨x.1, inZ_of_mem A hq x.2⟩ ⟨y.1, inZ_of_mem A hq y.2⟩ then 1 else 0 := by
  rw [DC_apply]
  have hxy : y.1 ∈ sccOf A x.1 := by rw [sccOf_eq_of_mem A x.2]; exact y.2
  exact DxN_eq_ite_muZ A (x := ⟨x.1, inZ_of_mem A hq x.2⟩) (y := ⟨y.1, inZ_of_mem A hq y.2⟩) hxy w

/-- One step `s ↦ s μ(b)` of the DFA of forward states (the DFA that follows the forward states `s_t := μ(ω_{(0,t]})` of Section 12.1). -/
def muStep (s : BRel (ZIdx A)) (b : Fin 2) : BRel (ZIdx A) := s * muZ A [b]

theorem foldl_muStep (w : List (Fin 2)) : ∀ s, w.foldl (muStep A) s = s * muZ A w := by
  induction w with
  | nil => intro s; simp [muZ_nil]
  | cons b w ih =>
    intro s
    rw [List.foldl_cons, ih, muStep, mul_assoc, ← muZ_append]; rfl

end Mon

/-! ## §4 `u♯` and the killing property -/

section Sharp

variable {Q : Type*} [Fintype Q] [DecidableEq Q] (A : ValAuto Q)

/-- **`u♯`** (Definition 12.2): the type `e := μ(u♯)` is an idempotent of the minimal ideal `\mathcal K` of `\mathcal M`, and `u♯` is non-empty and contains `u*`
(`IsUStar` of `CompartmentPi.lean`, Lemma 10.7: a word whose type on all indices is an idempotent of the minimal ideal of the type monoid). The condition
"a power of `u*vu*` ending with `u*`" of an earlier written form is not needed, since no greedy choice is made. Non-emptiness is used to kill trivial components. -/
structure Sharp (K : Set (BRel (ZIdx A))) (u : List (Fin 2)) (e : BRel (ZIdx A)) : Prop where
  minIdeal : IsMinIdeal (muMon A) K
  mem : e ∈ K
  idem : e * e = e
  mu_eq : muZ A u = e
  ne_nil : u ≠ []
  ustar : ∃ v, IsUStar A v ∧ v <:+: u

/-- `u♯` exists: an idempotent power of `u* v [0]` (`μ(v) ∈ \mathcal K`). -/
theorem exists_sharp : ∃ K u e, Sharp A K u e := by
  obtain ⟨K, hK⟩ := MinIdeal.exists_minIdeal (muMon A)
  obtain ⟨X, hX⟩ := hK.1.1
  obtain ⟨v, hv⟩ := exists_muZ_of_mem A (hK.1.2.1 hX)
  obtain ⟨us, hus⟩ := exists_ustar A
  set x := us ++ v ++ [0]
  have hxK : muZ A x ∈ K := by
    have h1 : muZ A (us ++ v) ∈ K := by
      rw [muZ_append, hv]; exact minIdeal_mul_mem_left hK (muZ_mem A us) hX
    have h2 : muZ A (us ++ v) * muZ A [0] ∈ K := minIdeal_mul_mem_right hK (muZ_mem A [0]) h1
    simpa only [x, muZ_append] using h2
  obtain ⟨n, hn, hidem⟩ := MinIdeal.exists_idem_pow (muZ A x)
  obtain ⟨n', rfl⟩ := Nat.exists_eq_add_of_lt hn
  refine ⟨K, (List.replicate (0 + n' + 1) x).flatten, muZ A x ^ (0 + n' + 1), ⟨hK, ?_, hidem, ?_, ?_, ?_⟩⟩
  · exact hK.1.pow_mem hxK (0 + n')
  · exact muZ_flatten_replicate A _ x
  · rw [List.replicate_succ', List.flatten_append]
    simp [x]
  · refine ⟨us, hus, ?_⟩
    rw [List.replicate_succ, List.flatten_cons]
    exact ⟨[], v ++ [0] ++ (List.replicate (0 + n') x).flatten, by simp [x]⟩

/-- `μ((u♯)^R) = e` (`R ≥ 1`). -/
theorem Sharp.mu_pow {K : Set (BRel (ZIdx A))} {u : List (Fin 2)} {e : BRel (ZIdx A)} (hS : Sharp A K u e)
    {R : ℕ} (hR : 1 ≤ R) : muZ A (List.replicate R u).flatten = e := by
  rw [muZ_flatten_replicate, hS.mu_eq]
  obtain ⟨R', rfl⟩ := Nat.exists_eq_add_of_le' hR
  induction R' with
  | zero => simp
  | succ R' ih => rw [pow_succ, ih (by omega), hS.idem]

/-- **The killing property** (Lemma 12.3 (i); after internal review): if all components are 0/1, then the strongly connected component of a relevant index `q`
outside `Q_s` has `D^C_{u♯} = 0`. A trivial component (without internal edge) gives 0 for non-empty words, and a non-survivable 0/1 component gives 0 by `u*`
(`ustar_kills`, `DC_eq_zero_of_infix` of `CompartmentPi.lean`). -/
theorem Sharp.kills (h01 : ∀ C, IsComp A C → ZeroOne A C) {K : Set (BRel (ZIdx A))} {u : List (Fin 2)}
    {e : BRel (ZIdx A)} (hS : Sharp A K u e) {q : Q} (hq : Rel A q) (hz : ¬ InZ A q) :
    DC A (sccOf A q) u = 0 := by
  by_cases hE : HasEdge A (sccOf A q)
  · have hns : ¬ Survivable A (sccOf A q) := fun hs => hz ⟨hq, hE, hs, h01 _ ⟨⟨q, hq, rfl⟩, hE⟩⟩
    obtain ⟨z, hzk⟩ := (not_survivable_iff A _).1 hns
    obtain ⟨v, hv, hvu⟩ := hS.ustar
    exact DC_eq_zero_of_infix A (ustar_kills A hv q hzk) hvu
  · obtain ⟨b, u', rfl⟩ := List.exists_cons_of_ne_nil hS.ne_nil
    have h0 := compMat_eq_zero_of_not_hasEdge A q hE b
    show Rigid.DxN (compMat A (sccOf A q)) (b :: u') = 0
    rw [DxN_cons', h0, zero_mul]

/-- The killing property, in the form for words containing `u♯`. -/
theorem Sharp.kills_infix (h01 : ∀ C, IsComp A C → ZeroOne A C) {K : Set (BRel (ZIdx A))} {u : List (Fin 2)}
    {e : BRel (ZIdx A)} (hS : Sharp A K u e) {q : Q} (hq : Rel A q) (hz : ¬ InZ A q) {w : List (Fin 2)}
    (hw : u <:+: w) : DC A (sccOf A q) w = 0 :=
  DC_eq_zero_of_infix A (hS.kills A h01 hq hz) hw

/-- **Recurrence of forward states**: if `s ∈ \mathcal K`, one can return from `s μ(w)` to `s` by some word `w'` (every state reachable from `s` in the
DFA `muStep` can return to `s`; material for `Recurrent` of Section 12.4). -/
theorem muZ_recurrent {K : Set (BRel (ZIdx A))} (hK : IsMinIdeal (muMon A) K) {s : BRel (ZIdx A)} (hs : s ∈ K)
    (w : List (Fin 2)) : ∃ w', s * muZ A w * muZ A w' = s := by
  obtain ⟨c, hc, hsc⟩ := right_stable hK hs (muZ_mem A w)
  obtain ⟨w', rfl⟩ := exists_muZ_of_mem A hc
  exact ⟨w', hsc⟩

/-- The type of a word containing an occurrence of `u♯` lies in `\mathcal K` (the forward state lies in `\mathcal K` after `τ`). -/
theorem Sharp.muZ_mem_K {K : Set (BRel (ZIdx A))} {u : List (Fin 2)} {e : BRel (ZIdx A)} (hS : Sharp A K u e)
    {w : List (Fin 2)} (hw : u <:+: w) : muZ A w ∈ K := by
  obtain ⟨s, t, rfl⟩ := hw
  rw [muZ_append, muZ_append, hS.mu_eq]
  exact minIdeal_mul_mem_right hS.minIdeal (muZ_mem A t) (minIdeal_mul_mem_left hS.minIdeal (muZ_mem A s) hS.mem)

end Sharp

/-! ## §5 Elements of intervals (Lemma 12.4, any occurrence) -/

section Theta

variable {Q : Type*} [Fintype Q] [DecidableEq Q] (A : ValAuto Q)

/-- The word `u` occurs in `ω` at the letter position `i` (letters `i, …, i + |u| - 1`, time interval `(i, i + |u|]`). -/
def occAt (u ω : List (Fin 2)) (i : ℕ) : Prop := i + u.length ≤ ω.length ∧ (ω.drop i).take u.length = u

instance (u ω : List (Fin 2)) (i : ℕ) : Decidable (occAt u ω i) := by unfold occAt; infer_instance

theorem occAt_le {u ω : List (Fin 2)} {i : ℕ} (h : occAt u ω i) : i + u.length ≤ ω.length := h.1

/-- For `a ≤ c ≤ b`, the word `ω_{(a,b]}` of the interval `(a, b]` is `ω_{(a,c]} ++ ω_{(c,b]}`. -/
theorem seg_split (ω : List (Fin 2)) {a c b : ℕ} (hac : a ≤ c) (hcb : c ≤ b) :
    (ω.drop a).take (b - a) = (ω.drop a).take (c - a) ++ (ω.drop c).take (b - c) := by
  rw [show b - a = (c - a) + (b - c) by omega, List.take_add, List.drop_drop]
  congr 3; omega

theorem take_split (ω : List (Fin 2)) {a b : ℕ} (hab : a ≤ b) :
    ω.take b = ω.take a ++ (ω.drop a).take (b - a) := by
  rw [show b = a + (b - a) by omega, List.take_add]
  congr 2; omega

/-- **Lemma 12.4 (elements of intervals)** (for any occurrence): suppose that the interval `(a, b]` contains the whole occurrence of `u♯` at position `i`
(`a ≤ i`, `i + |u♯| ≤ b`), and let `r := i + |u♯|` and `A := μ(ω_{(a,r]})`. Then
`μ(ω_{(a,b]}) = Θ(s_a, A, s_b)` (`s_t := μ(ω_{(0,t]})`; `Θ` is a fixed function determined by `e` alone). -/
theorem theta_spec {K : Set (BRel (ZIdx A))} {u : List (Fin 2)} {e : BRel (ZIdx A)} (hS : Sharp A K u e)
    (ω : List (Fin 2)) {a i b : ℕ} (hai : a ≤ i) (hib : i + u.length ≤ b) (hocc : occAt u ω i) :
    muZ A ((ω.drop a).take (b - a)) =
      theta e (muZ A (ω.take a)) (muZ A ((ω.drop a).take (i + u.length - a))) (muZ A (ω.take b)) := by
  set r := i + u.length
  have hseg := seg_split ω (show a ≤ r by omega) hib
  have hx : (ω.drop a).take (r - a) = (ω.drop a).take (i - a) ++ u := by
    rw [seg_split ω hai (show i ≤ r by omega)]
    congr 1
    rw [show r - i = u.length by omega]; exact hocc.2
  set Am := muZ A ((ω.drop a).take (r - a))
  have hAe : Am * e = Am := by
    simp only [Am]; rw [hx, muZ_append, hS.mu_eq, mul_assoc, hS.idem]
  set y₀ := e * muZ A ((ω.drop r).take (b - r))
  have hy₀ : e * y₀ = y₀ := by simp only [y₀]; rw [← mul_assoc, hS.idem]
  have hval : muZ A ((ω.drop a).take (b - a)) = Am * y₀ := by
    rw [hseg, muZ_append]; simp only [y₀, Am]; rw [← mul_assoc, hAe]
  have hsb : muZ A (ω.take b) = muZ A (ω.take a) * Am * y₀ := by
    rw [take_split ω (show a ≤ b by omega), muZ_append, hval, mul_assoc]
  rw [hsb, hval]
  exact (theta_eq hS.minIdeal hS.mem hS.idem (muZ_mem A _) (muZ_mem A _) hAe hy₀).symm

open Classical in
/-- **The weight of a long sojourn** (the statement "the indicator of a long sojourn is an entry of `Θ`" used for Proposition 12.11; Lemma 12.4 (ii)): if `x, y`
lie in the same component of `Q_s` and the interval `(a, b]` contains the occurrence of `u♯` at position `i`, then `(B_{ω_{(a,b]}})_{xy} = [Θ(s_a, A, s_b)_{xy}]`. -/
theorem stay_eq_theta {K : Set (BRel (ZIdx A))} {u : List (Fin 2)} {e : BRel (ZIdx A)} (hS : Sharp A K u e)
    (ω : List (Fin 2)) {a i b : ℕ} (hai : a ≤ i) (hib : i + u.length ≤ b) (hocc : occAt u ω i)
    {x y : ZIdx A} (hxy : y.1 ∈ sccOf A x.1) :
    Rigid.DxN A.B ((ω.drop a).take (b - a)) x.1 y.1 =
      if theta e (muZ A (ω.take a)) (muZ A ((ω.drop a).take (i + u.length - a))) (muZ A (ω.take b)) x y
      then 1 else 0 := by
  rw [DxN_eq_ite_muZ A hxy, theta_spec A hS ω hai hib hocc]

end Theta

end Collatz.Arctic.NatQ5.W3c
