/-
Proposition 9.5 of the paper, continued. The definitions and the parts of (i), (ii) are in `NatExample.lean`.

* §7 (iii) The residue component: the restriction `resPart` to the residue indices (2, 3, 4 in the paper, `1, 2, 3` in `Fin 4`; after the
  restriction the index is the residue `r ∈ Fin 3`). The restrictions of `M_f` and `M_t` are
  twice the permutation matrices of `r ↦ 2r` and `r ↦ 2r + 1 (mod 3)` (the transpositions `(1 2)` and `(0 1)`); every product of length `k` of
  restrictions is `2^k` times a permutation matrix (growth rate log 2); all six permutations occur in nonempty products, and no positive matrix occurs ((P) fails). The residue indices
  have no edge to or from the slow path (index 0), are strongly connected, are entered from the left end (`1 + r_in`) and are left at the right end (`1 + r_out`).
* §8 Remark (the form of Paper I): with the start and end vectors `e₀ + e₁` (`e₁ + e₂` in the paper), reading all binary digits, including the leading one,
  from the most significant end gives `φ(n) = 1 + 2^{ℓ(n)}[3 ∣ n]` (`n ≥ 1`), and `φ(T n) ≤ φ(n)` for `n ≥ 2`.
* §9 Summary: `prop_10_1_T`, `prop_10_1_H`, `prop_10_1_RH` ((i)-(iii) of Proposition 9.5) and `prop_10_1_remark` (the `φ` of the remark).
-/
import CollatzProof.Arctic.NatExample

namespace Collatz.Arctic.NatExample

open Collatz.Arctic Matrix

/-! ## §7 (iii) The residue component -/

/-- The restriction to the residue indices (the index `i` goes to `i + 1`). -/
def resPart (A : Matrix (Fin 4) (Fin 4) ℕ) : Matrix (Fin 3) (Fin 3) ℕ := Matrix.of fun i j => A i.succ j.succ

/-- The letter of a binary digit (`false` = `f`, `true` = `t`). -/
def digitL (b : Bool) : Letter := if b then Letter.t else Letter.f

/-- The product of restrictions `N_{b₁} ⋯ N_{bₖ}` (an element of the semigroup generated by the restrictions, Section 2 of Paper II). -/
def resProd (I : Letter → NAff 4) (w : List Bool) : Matrix (Fin 3) (Fin 3) ℕ :=
  (w.map fun b => resPart (I (digitL b)).M).prod

/-- The permutation `r ↦ 2r + b mod 3` of the residues for the digit `b`. -/
def sigmaB (b : Bool) : Equiv.Perm (Fin 3) := if b then Equiv.swap 0 1 else Equiv.swap 1 2

theorem sigmaB_apply : ∀ (b : Bool) (r : Fin 3), (sigmaB b r).val = (2 * r.val + b.toNat) % 3 := by
  decide

theorem interp_digit (rin rout : ℕ) (b : Bool) : (interp rin rout (digitL b)).M = matB b.toNat := by
  cases b <;> rfl

theorem resPart_digit (rin rout : ℕ) (b : Bool) :
    resPart (interp rin rout (digitL b)).M = 2 • (sigmaB b).permMatrix ℕ := by
  rw [interp_digit]; cases b <;> decide

/-- The permutation of a product (in the order given by `permMatrix (σ * τ) = permMatrix τ * permMatrix σ`). -/
def permOf : List Bool → Equiv.Perm (Fin 3)
  | [] => 1
  | b :: w => permOf w * sigmaB b

theorem resProd_eq (rin rout : ℕ) (w : List Bool) :
    resProd (interp rin rout) w = 2 ^ w.length • (permOf w).permMatrix ℕ := by
  induction w with
  | nil => simp [resProd, permOf]
  | cons b w ih =>
    have h : resProd (interp rin rout) (b :: w) =
        resPart (interp rin rout (digitL b)).M * resProd (interp rin rout) w := by
      simp [resProd]
    rw [h, ih, resPart_digit, permOf, permMatrix_mul, Matrix.smul_mul, Matrix.mul_smul, smul_smul,
      List.length_cons, pow_succ']

theorem permMatrix_apply' (σ : Equiv.Perm (Fin 3)) (i j : Fin 3) :
    σ.permMatrix ℕ i j = if σ i = j then 1 else 0 := by
  simp [Equiv.Perm.permMatrix, PEquiv.toMatrix_apply]

theorem resProd_apply (rin rout : ℕ) (w : List Bool) (i j : Fin 3) :
    resProd (interp rin rout) w i j = if permOf w i = j then 2 ^ w.length else 0 := by
  rw [resProd_eq, Matrix.smul_apply, permMatrix_apply']
  split_ifs <;> simp

/-- A list of nonempty words (their values under `permOf` are all six permutations). -/
def wordsAll : List (List Bool) :=
  [[false, false], [false], [true], [false, true], [true, false], [false, true, false]]

theorem permOf_surj : ∀ σ : Equiv.Perm (Fin 3), ∃ w ∈ wordsAll, permOf w = σ := by decide +kernel

theorem wordsAll_ne_nil : ∀ w ∈ wordsAll, w ≠ [] := by decide

/-- The content of (iii) (a statement about the digit matrices of the interpretation `I`). -/
def ResidueComponent (I : Letter → NAff 4) : Prop :=
  -- the restrictions are twice the permutation matrices of the transpositions `(1 2)` (`r ↦ 2r`) and `(0 1)` (`r ↦ 2r + 1`)
  resPart (I Letter.f).M = 2 • (Equiv.swap (1 : Fin 3) 2).permMatrix ℕ ∧
  resPart (I Letter.t).M = 2 • (Equiv.swap (0 : Fin 3) 1).permMatrix ℕ ∧
  (∀ r : Fin 3, (Equiv.swap (1 : Fin 3) 2 r).val = 2 * r.val % 3) ∧
  (∀ r : Fin 3, (Equiv.swap (0 : Fin 3) 1 r).val = (2 * r.val + 1) % 3) ∧
  -- every product of length `k` of restrictions is `2^k` times a permutation matrix (growth rate log 2)
  (∀ w : List Bool, ∃ σ : Equiv.Perm (Fin 3), resProd I w = 2 ^ w.length • σ.permMatrix ℕ) ∧
  -- all six permutations occur in nonempty products
  (∀ σ : Equiv.Perm (Fin 3), ∃ w : List Bool, w ≠ [] ∧ resProd I w = 2 ^ w.length • σ.permMatrix ℕ) ∧
  -- exactly one positive entry in each row and each column, and no positive matrix ((P) fails)
  (∀ w : List Bool, ∀ i, ∃! j, 0 < resProd I w i j) ∧
  (∀ w : List Bool, ∀ j, ∃! i, 0 < resProd I w i j) ∧
  (¬ ∃ w : List Bool, ∀ i j, 0 < resProd I w i j) ∧
  -- no edge between the slow path (index 0) and the residue indices, and the residue indices are strongly connected
  (∀ (b : Bool) (i : Fin 3), (I (digitL b)).M 0 i.succ = 0 ∧ (I (digitL b)).M i.succ 0 = 0) ∧
  (∀ i j : Fin 3, ∃ w : List Bool, w ≠ [] ∧ 0 < resProd I w i j)

theorem residueComponent (rin rout : ℕ) : ResidueComponent (interp rin rout) := by
  have hsurj : ∀ σ : Equiv.Perm (Fin 3), ∃ w : List Bool, w ≠ [] ∧ permOf w = σ := fun σ => by
    obtain ⟨w, hw, h⟩ := permOf_surj σ
    exact ⟨w, wordsAll_ne_nil w hw, h⟩
  refine ⟨resPart_digit rin rout false, resPart_digit rin rout true, by decide, by decide,
    fun w => ⟨permOf w, resProd_eq rin rout w⟩, fun σ => ?_, fun w i => ?_, fun w j => ?_, ?_, ?_, ?_⟩
  · obtain ⟨w, hw, h⟩ := hsurj σ
    exact ⟨w, hw, h ▸ resProd_eq rin rout w⟩
  · refine ⟨permOf w i, by simp [resProd_apply], fun j hj => ?_⟩
    have hj : 0 < resProd (interp rin rout) w i j := hj
    rw [resProd_apply] at hj
    split_ifs at hj with h
    · exact h.symm
    · exact absurd hj (lt_irrefl 0)
  · refine ⟨(permOf w).symm j, by simp [resProd_apply], fun i hi => ?_⟩
    have hi : 0 < resProd (interp rin rout) w i j := hi
    rw [resProd_apply] at hi
    split_ifs at hi with h
    · rw [← h, Equiv.symm_apply_apply]
    · exact absurd hi (lt_irrefl 0)
  · rintro ⟨w, hw⟩
    have hne : permOf w 0 ≠ permOf w 0 + 1 := by
      intro h'; have := congrArg (· - permOf w 0) h'; simp at this
    have h := hw 0 (permOf w 0 + 1)
    rw [resProd_apply] at h
    simp only [hne, ↓reduceIte] at h
    exact lt_irrefl 0 h
  · intro b i
    rw [interp_digit]
    revert i; cases b <;> decide
  · intro i j
    obtain ⟨w, hw, h⟩ := hsurj (Equiv.swap i j)
    refine ⟨w, hw, ?_⟩
    rw [resProd_apply, h, Equiv.swap_apply_left]
    simp only [↓reduceIte]
    exact Nat.pow_pos (by norm_num)

/-! ## §8 Remark: the form of Paper I (reading all digits, including the leading one) -/

/-- `φ(n) = u ⬝ M_{b_{ℓ-1}} ⋯ M_{b₀} ⬝ c` with `u = c = e₀ + e₁` (`e₁ + e₂` in the paper), the digits read from the most significant one. -/
def phiI (n : ℕ) : ℕ := (![1, 1, 0, 0] ᵥ* ((Nat.digits 2 n).reverse.map matB).prod) ⬝ᵥ ![1, 1, 0, 0]

theorem rowI (n : ℕ) (hn : 1 ≤ n) :
    ![1, 1, 0, 0] ᵥ* ((Nat.digits 2 n).reverse.map matB).prod = resRow (2 ^ (Nat.digits 2 n).length) n := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    rcases Nat.lt_or_ge n 2 with h | h
    · obtain rfl : n = 1 := by omega
      have hu : (![1, 1, 0, 0] : Fin 4 → ℕ) = resRow 1 0 := by decide
      rw [hu]
      simpa using resRow_vecMul_matB 1 0 1 (by norm_num)
    · have hy : 1 ≤ n / 2 := by omega
      have hb : n % 2 < 2 := Nat.mod_lt _ (by norm_num)
      have hn' : n = 2 * (n / 2) + n % 2 := by omega
      rw [hn', digits_two_mul_add _ _ hy hb, List.reverse_cons, List.map_append, List.prod_append,
        List.map_singleton, List.prod_singleton, ← vecMul_vecMul, ih (n / 2) (by omega) hy,
        resRow_vecMul_matB _ _ _ hb, List.length_cons, pow_succ']

theorem phiI_eq (n : ℕ) (hn : 1 ≤ n) : phiI n = 1 + if n % 3 = 0 then 2 ^ (Nat.digits 2 n).length else 0 := by
  have hc : (![1, 1, 0, 0] : Fin 4 → ℕ) = vecR 0 := by decide
  rw [phiI, rowI n hn, hc, resRow_dot_vecR _ _ _ (by norm_num)]

/-- `φ(T n) ≤ φ(n)` for `n ≥ 2`. -/
theorem phiI_T_noninc (n : ℕ) (hn : 2 ≤ n) : phiI (T n) ≤ phiI n := by
  rcases Nat.even_or_odd' n with ⟨y, rfl | rfl⟩
  · have hT : T (2 * y) = y := by simp [T]
    have hd : (Nat.digits 2 (2 * y)).length = (Nat.digits 2 y).length + 1 := by
      have := digits_two_mul_add y 0 (by omega) (by norm_num)
      rw [add_zero] at this; rw [this, List.length_cons]
    rw [hT, phiI_eq y (by omega), phiI_eq (2 * y) (by omega), hd]
    have hpow : 2 ^ (Nat.digits 2 y).length ≤ 2 ^ ((Nat.digits 2 y).length + 1) :=
      Nat.pow_le_pow_right (by norm_num) (by omega)
    split_ifs <;> omega
  · have hT : T (2 * y + 1) = 3 * y + 2 := by simp [T]; omega
    have h3 : (3 * y + 2) % 3 ≠ 0 := by omega
    rw [hT, phiI_eq (3 * y + 2) (by omega), phiI_eq (2 * y + 1) (by omega)]
    simp only [h3, ↓reduceIte, add_zero]
    omega

/-- A check of small values (from the definitions by `decide`, independently of the formulas of the theorems). `6 = 110₂`, `7 = 111₂`. -/
example : PhiN IT (can 6) = 5 ∧ PhiN IT (can 7) = 1 ∧ PhiN IH (can 7) = 5 ∧ PhiN IRH (RH.canRH 7) = 9 ∧
    phiI 6 = 9 ∧ phiI 7 = 1 := by decide +kernel

/-! ## §9 Summary (Proposition 9.5 of the paper and the remark after it) -/

/-- Proposition 9.5, $\mathcal T$ (`r_in = 1`, `r_out = 0`). (i) The 11 rules are weakly oriented, the first components of `v` of the two sides agree,
no rule is strictly oriented, and `(M_s)₀₀ = 1`. (ii) The formula for the values, and that they do not increase along $T$. (iii) The residue component (entered from the left end at the index
`1 + r_in`, left through the index `1 + r_out` of `v_.` at the right end). -/
theorem prop_10_1_T :
    (∀ ρ ∈ rulesST, NWeak IT ρ) ∧ (∀ ρ ∈ rulesST, (evN IT ρ.lhs).v 0 = (evN IT ρ.rhs).v 0) ∧
    (∀ ρ ∈ rulesST, ¬ NStrict IT ρ) ∧ (∀ s, (IT s).M 0 0 = 1) ∧
    (∀ n, 1 ≤ n → PhiN IT (can n) = 1 + if n % 3 = 0 then 2 ^ ((Nat.digits 2 n).length - 1) else 0) ∧
    (∀ n, 2 ≤ n → PhiN IT (can (T n)) ≤ PhiN IT (can n)) ∧
    ResidueComponent IT ∧ (IT Letter.lft).M 0 (resIdx 1) = 1 ∧ (IT Letter.rgt).v (resIdx 0) = 1 :=
  ⟨weak_T, v0_T, fun ρ hρ => not_strict_of_v0 IT ρ (v0_T ρ hρ), interp_M00 1 0, phi_can_T, phi_T_noninc,
    residueComponent 1 0, by decide, by decide⟩

/-- Proposition 9.5, $\mathcal H$ (`r_in = 1`, `r_out = 1`). The values do not increase along $H$ at the points of `HModel.HDom`. -/
theorem prop_10_1_H :
    (∀ ρ ∈ HTPDB.rulesHT, NWeak IH ρ) ∧ (∀ ρ ∈ HTPDB.rulesHT, (evN IH ρ.lhs).v 0 = (evN IH ρ.rhs).v 0) ∧
    (∀ ρ ∈ HTPDB.rulesHT, ¬ NStrict IH ρ) ∧ (∀ s, (IH s).M 0 0 = 1) ∧
    (∀ n, 1 ≤ n → PhiN IH (can n) = 1 + if n % 3 = 1 then 2 ^ ((Nat.digits 2 n).length - 1) else 0) ∧
    (∀ n, HModel.HDom n → PhiN IH (can (HModel.Hmap n)) ≤ PhiN IH (can n)) ∧
    ResidueComponent IH ∧ (IH Letter.lft).M 0 (resIdx 1) = 1 ∧ (IH Letter.rgt).v (resIdx 1) = 1 :=
  ⟨weak_H, v0_H, fun ρ hρ => not_strict_of_v0 IH ρ (v0_H ρ hρ), interp_M00 1 1, phi_can_H, phi_H_noninc,
    residueComponent 1 1, by decide, by decide⟩

/-- Proposition 9.5, $R_H$ (12 rules, `r_in = 0`, `r_out = 1`, `L` is `lft`). -/
theorem prop_10_1_RH :
    (∀ ρ ∈ RH.rulesRH, NWeak IRH ρ) ∧ (∀ ρ ∈ RH.rulesRH, (evN IRH ρ.lhs).v 0 = (evN IRH ρ.rhs).v 0) ∧
    (∀ ρ ∈ RH.rulesRH, ¬ NStrict IRH ρ) ∧ (∀ s, (IRH s).M 0 0 = 1) ∧
    (∀ n, 1 ≤ n → PhiN IRH (RH.canRH n) = 1 + if n % 3 = 1 then 2 ^ (Nat.digits 2 n).length else 0) ∧
    (∀ n, HModel.HDom n → PhiN IRH (RH.canRH (HModel.Hmap n)) ≤ PhiN IRH (RH.canRH n)) ∧
    ResidueComponent IRH ∧ (IRH Letter.lft).M 0 (resIdx 0) = 1 ∧ (IRH Letter.rgt).v (resIdx 1) = 1 :=
  ⟨weak_RH, v0_RH, fun ρ hρ => not_strict_of_v0 IRH ρ (v0_RH ρ hρ), interp_M00 0 1, phi_canRH,
    phi_RH_noninc, residueComponent 0 1, by decide, by decide⟩

/-- The remark (the form of Paper I): `φ(n) = 1 + 2^{ℓ(n)}[3 ∣ n]` (`n ≥ 1`), and `φ(T n) ≤ φ(n)` for `n ≥ 2`. -/
theorem prop_10_1_remark :
    (∀ n, 1 ≤ n → phiI n = 1 + if n % 3 = 0 then 2 ^ (Nat.digits 2 n).length else 0) ∧
    (∀ n, 2 ≤ n → phiI (T n) ≤ phiI n) :=
  ⟨phiI_eq, phiI_T_noninc⟩

end Collatz.Arctic.NatExample
